--Consulta 1
SELECT NOMBRE_ARTICULO,RESUMEN_ARTICULO 
FROM ARTICULO 
WHERE NOMBRE_ARTICULO LIKE 'O%';

--Consulta 2
SELECT RUT_AUTOR, COUNT(RUT_AUTOR) AS cant_articulos_Publicados 
FROM PUBLICACION
GROUP BY RUT_AUTOR

--Consulta 3
SELECT NOMBRE_ARTICULO
FROM TOPICO_ARTICULO INNER JOIN ARTICULO ON ARTICULO.ID_ARTICULO = TOPICO_ARTICULO.ID_ARTICULO
GROUP BY ARTICULO.ID_ARTICULO
HAVING COUNT(TOPICO_ARTICULO.ID_ARTICULO)>1

--Consulta 4
SELECT NOMBRE_ARTICULO, AUTOR.*
FROM (ARTICULO INNER JOIN PUBLICACION ON ARTICULO.ID_ARTICULO = PUBLICACION.ID_ARTICULO)
INNER JOIN AUTOR ON AUTOR.RUT_AUTOR = PUBLICACION.RUT_AUTOR
WHERE PUBLICACION.ES_CONTACTO = TRUE AND NOMBRE_ARTICULO LIKE '%Software%' --Adaptar

--Consulta 5
SELECT NOMBRE_REVISOR, COUNT(ID_ARTICULO) AS cant_articulos_asignados
FROM REVISOR INNER JOIN REVISION ON REVISOR.RUT_REVISOR = REVISION.RUT_REVISOR
GROUP BY NOMBRE_REVISOR

--Consulta 6
SELECT NOMBRE_REVISOR
FROM REVISOR INNER JOIN REVISION ON REVISOR.RUT_REVISOR = REVISION.RUT_REVISOR
GROUP BY NOMBRE_REVISOR
HAVING COUNT(ID_ARTICULO) > 3

--Consulta 7
SELECT NOMBRE_ARTICULO, NOMBRE_REVISOR
FROM (REVISION INNER JOIN REVISOR ON REVISION.RUT_REVISOR = REVISOR.RUT_REVISOR) INNER JOIN ARTICULO ON ARTICULO.ID_ARTICULO = REVISION.ID_ARTICULO
WHERE NOMBRE_ARTICULO LIKE '%Gestion%' --Adaptar
ORDER BY NOMBRE_ARTICULO ASC

--Consulta 8
SELECT NOMBRE_TOPICO, COUNT(RUT_REVISOR) AS cant_especialistas
FROM TOPICO INNER JOIN TOPICO_ESP ON TOPICO.ID_TOPICO = TOPICO_ESP.ID_TOPICO
GROUP BY NOMBRE_TOPICO

--Consulta 9
SELECT DISTINCT ID_ARTICULO,FECHA_PUBLICACION FROM PUBLICACION
ORDER BY FECHA_PUBLICACION ASC
LIMIT 10

--Consulta 10
SELECT NOMBRE_ARTICULO FROM
ARTICULO INNER JOIN REVISION ON ARTICULO.ID_ARTICULO = REVISION.ID_ARTICULO
WHERE RUT_REVISOR IN (SELECT RUT_REVISOR
FROM REVISION
GROUP BY RUT_REVISOR
HAVING COUNT(ID_ARTICULO) > 3
ORDER BY COUNT(ID_ARTICULO) DESC)
GROUP BY NOMBRE_ARTICULO
HAVING COUNT(NOMBRE_ARTICULO)=3
ORDER BY NOMBRE_ARTICULO ASC